pub mod auth;
pub mod error;
pub mod handlers;

use axum::{
    Router,
    http::{Method, header},
    routing::{any, delete, get, patch, post, put},
};
use tower_http::cors::{Any, CorsLayer};

use crate::state::AppState;

pub fn router(state: AppState) -> Router {
    Router::new()
        .route("/health", get(handlers::health::healthcheck))
        .route("/api/v1/health", get(handlers::health::healthcheck))
        .route("/metrics", get(handlers::health::metrics))
        .route("/api/v1/settings", get(handlers::settings::settings))
        .route(
            "/api/v1/network/protection",
            get(handlers::network_protection::protection),
        )
        .route(
            "/api/v1/network/protection/status",
            get(handlers::network_protection::protection_status),
        )
        .route(
            "/api/v1/network/protection/preflight",
            get(handlers::network_protection::preflight),
        )
        .route(
            "/api/v1/network/protection/switch",
            post(handlers::network_protection::switch_profile),
        )
        .route(
            "/api/v1/network/protection/first-run",
            post(handlers::network_protection::first_run_setup),
        )
        .route(
            "/api/v1/network/protection/events",
            get(handlers::network_protection::events),
        )
        .route(
            "/api/v1/network/protection/profiles",
            get(handlers::network_protection::profiles),
        )
        .route(
            "/api/v1/network/protection/import/wireguard",
            post(handlers::network_protection::import_wireguard),
        )
        .route(
            "/api/v1/network/protection/import/openvpn",
            post(handlers::network_protection::import_openvpn),
        )
        .route(
            "/api/v1/network/protection/provider-presets",
            get(handlers::network_protection::provider_presets),
        )
        .route(
            "/api/v1/network/protection/qbittorrent/listen-port-sync",
            get(handlers::network_protection::qbittorrent_listen_port_sync),
        )
        .route(
            "/api/v1/network/protection/qbittorrent/listen-port-sync/apply",
            post(handlers::network_protection::apply_qbittorrent_listen_port_sync),
        )
        .route(
            "/api/v1/network/protection/warp/disclosure",
            get(handlers::network_protection::warp_disclosure),
        )
        .route(
            "/api/v1/network/protection/warp/profile",
            post(handlers::network_protection::ensure_warp_profile),
        )
        .route(
            "/api/v1/network/protection/warp/enroll",
            post(handlers::network_protection::ensure_warp_profile),
        )
        .route(
            "/api/v1/network/protection/warp/reset",
            post(handlers::network_protection::reset_warp_profile),
        )
        .route(
            "/api/v1/network/protection/warp/diagnostics",
            get(handlers::network_protection::warp_diagnostics),
        )
        .route(
            "/api/v1/download-broker/downloaders",
            get(handlers::download_broker::list_downloaders),
        )
        .route(
            "/api/v1/download-broker/routes",
            get(handlers::download_broker::list_routes),
        )
        .route(
            "/api/v1/download-broker/routes/:logical_id",
            put(handlers::download_broker::update_route),
        )
        .route(
            "/api/v1/download-broker/:logical_id/progress",
            get(handlers::download_broker::progress),
        )
        .route(
            "/api/v1/download-broker/:logical_id/submit",
            post(handlers::download_broker::submit),
        )
        .route(
            "/api/v1/acquisition/candidates/providers",
            get(handlers::acquisition_sources::list_candidate_providers),
        )
        .route(
            "/api/v1/acquisition/candidates/search",
            post(handlers::acquisition_sources::search_candidates),
        )
        .route(
            "/api/v1/acquisition/subscriptions",
            get(handlers::acquisition_subscriptions::list_acquisition_subscriptions)
                .post(handlers::acquisition_subscriptions::create_acquisition_subscription),
        )
        .route(
            "/api/v1/acquisition/intents",
            post(handlers::acquisition_subscriptions::create_acquisition_intent),
        )
        .route(
            "/api/v1/acquisition/subscriptions/:subscription_id",
            get(handlers::acquisition_subscriptions::get_acquisition_subscription)
                .patch(handlers::acquisition_subscriptions::patch_acquisition_subscription),
        )
        .route(
            "/api/v1/acquisition/subscriptions/:subscription_id/coverage",
            get(handlers::acquisition_review::acquisition_subscription_coverage),
        )
        .route(
            "/api/v1/acquisition/subscriptions/:subscription_id/targets",
            put(handlers::acquisition_subscriptions::upsert_acquisition_targets),
        )
        .route(
            "/api/v1/acquisition/releases",
            get(handlers::acquisition_review::list_acquisition_releases),
        )
        .route(
            "/api/v1/acquisition/releases/:release_id",
            get(handlers::acquisition_review::get_acquisition_release),
        )
        .route(
            "/api/v1/acquisition/releases/:release_id/approve",
            post(handlers::acquisition_review::approve_acquisition_release),
        )
        .route(
            "/api/v1/acquisition/releases/:release_id/reject",
            post(handlers::acquisition_review::reject_acquisition_release),
        )
        .route(
            "/api/v1/acquisition/releases/:release_id/retry",
            post(handlers::acquisition_review::retry_acquisition_release),
        )
        .route(
            "/api/v1/acquisition/targets/:target_id/state",
            patch(handlers::acquisition_subscriptions::patch_acquisition_target_state),
        )
        .route(
            "/api/v1/acquisition/targets/:target_id/submit",
            post(handlers::acquisition_subscriptions::submit_acquisition_target_candidate),
        )
        .route(
            "/api/v1/download-broker/:logical_id/items/:download_id",
            delete(handlers::download_broker::cancel),
        )
        .route(
            "/api/v1/extensions/catalog",
            get(handlers::extensions::catalog),
        )
        .route(
            "/api/v1/extensions/status-summary",
            get(handlers::extensions::status_summary),
        )
        .route(
            "/api/v1/extensions/:id/control-surface",
            get(handlers::extensions::get_extension_control_surface)
                .put(handlers::extensions::update_extension_control_surface_settings),
        )
        .route(
            "/api/v1/extensions/:id/control-surface/actions/:action_id",
            post(handlers::extensions::run_extension_control_action),
        )
        .route(
            "/api/v1/extensions/instances/:id/ui/start",
            get(handlers::extensions::start_extension_ui_session),
        )
        .route(
            "/api/v1/extensions/instances/:id/ui",
            any(handlers::extensions::proxy_extension_ui_root),
        )
        .route(
            "/api/v1/extensions/instances/:id/ui/",
            any(handlers::extensions::proxy_extension_ui_root),
        )
        .route(
            "/api/v1/extensions/instances/:id/ui/*path",
            any(handlers::extensions::proxy_extension_ui),
        )
        .route(
            "/api/v1/extensions/registries/refresh",
            post(handlers::extensions::refresh_catalog),
        )
        .route(
            "/api/v1/extensions/:id",
            get(handlers::extensions::get_extension),
        )
        .route(
            "/api/v1/extensions/install",
            post(handlers::extensions::install_extension),
        )
        .route(
            "/api/v1/extensions/:id/enable",
            post(handlers::extensions::enable_extension),
        )
        .route(
            "/api/v1/extensions/:id/disable",
            post(handlers::extensions::disable_extension),
        )
        .route(
            "/api/v1/extensions/:id/uninstall",
            post(handlers::extensions::uninstall_extension),
        )
        .route(
            "/api/v1/extensions/:id/instances",
            post(handlers::extensions::create_instance),
        )
        .route(
            "/api/v1/extensions/instances",
            get(handlers::extensions::list_instances),
        )
        .route(
            "/api/v1/extensions/instances/:id",
            patch(handlers::extensions::update_instance),
        )
        .route(
            "/api/v1/extensions/instances/:id",
            delete(handlers::extensions::delete_instance),
        )
        .route(
            "/api/v1/extensions/instances/:id/rollback",
            post(handlers::extensions::rollback_instance),
        )
        .route(
            "/api/v1/extensions/blueprints/apply",
            post(handlers::extensions::apply_blueprint),
        )
        .route(
            "/api/v1/extensions/plan/:id/confirm",
            post(handlers::extensions::confirm_plan),
        )
        .route(
            "/api/v1/extensions/plan/:id/cancel",
            post(handlers::extensions::cancel_plan),
        )
        .route(
            "/api/v1/extensions/reconcile/now",
            post(handlers::extensions::reconcile_now),
        )
        .route(
            "/api/v1/extensions/reconcile/latest",
            get(handlers::extensions::reconcile_latest),
        )
        .route(
            "/api/v1/extensions/runtime/reset",
            post(handlers::extensions::reset_runtime),
        )
        .route(
            "/api/v1/extensions/downloaders/profile",
            get(handlers::extensions::downloader_profile)
                .patch(handlers::extensions::update_downloader_profile),
        )
        .route(
            "/api/v1/extensions/runs",
            get(handlers::extensions::list_runs).delete(handlers::extensions::clear_runs),
        )
        .route(
            "/api/v1/extensions/desired-blueprints",
            get(handlers::extensions::list_desired_blueprints),
        )
        .route(
            "/api/v1/extensions/desired-blueprints",
            delete(handlers::extensions::clear_desired_blueprints),
        )
        .route(
            "/api/v1/extensions/runs/:id",
            get(handlers::extensions::run_detail),
        )
        .route("/api/v1/extensions/graph", get(handlers::extensions::graph))
        .route(
            "/api/v1/extensions/providers/:id/health",
            get(handlers::extensions::provider_health),
        )
        .route(
            "/api/v1/extensions/runtime/:id/logs",
            get(handlers::extensions::runtime_logs),
        )
        .route(
            "/api/v1/extensions/secrets",
            get(handlers::extensions::list_secrets),
        )
        .route(
            "/api/v1/extensions/secrets",
            post(handlers::extensions::create_secret),
        )
        .route(
            "/api/v1/extensions/secrets/:id",
            get(handlers::extensions::get_secret),
        )
        .route(
            "/api/v1/extensions/secrets/:id",
            patch(handlers::extensions::update_secret),
        )
        .route(
            "/api/v1/extensions/secrets/:id",
            delete(handlers::extensions::delete_secret),
        )
        .route(
            "/api/v1/extensions/secrets/:id/rotate",
            post(handlers::extensions::rotate_secret),
        )
        .route("/api/v1/auth/login", post(handlers::auth::login))
        .route("/api/v1/auth/signup", post(handlers::auth::signup))
        .route(
            "/api/v1/auth/reset/start",
            post(handlers::auth::start_password_reset),
        )
        .route(
            "/api/v1/auth/reset/complete",
            post(handlers::auth::complete_password_reset),
        )
        .route("/api/v1/library/items", get(handlers::library::list_items))
        .route(
            "/api/v1/library/owner-release/events",
            get(handlers::library::list_owner_release_events),
        )
        .route(
            "/api/v1/library/owner-release/reconcile",
            post(handlers::library::reconcile_owner_release_state),
        )
        .route(
            "/api/v1/library/items/:id",
            get(handlers::library::detail).delete(handlers::library::delete_item),
        )
        .route(
            "/api/v1/library/items/:id/owner-release/events",
            get(handlers::library::list_item_owner_release_events),
        )
        .route(
            "/api/v1/library/items/:id/restore-blocked-episodes",
            post(handlers::library::restore_blocked_episodes),
        )
        .route(
            "/api/v1/library/series/:id/seasons",
            get(handlers::library::list_seasons),
        )
        .route(
            "/api/v1/library/seasons/:id",
            get(handlers::library::season_detail),
        )
        .route(
            "/api/v1/library/seasons/:id/episodes",
            get(handlers::library::list_episodes),
        )
        .route(
            "/api/v1/library/episodes/:id",
            delete(handlers::library::delete_episode),
        )
        .route(
            "/api/v1/library/episodes/:id/restore",
            post(handlers::library::restore_episode),
        )
        .route("/api/v1/library/scan", post(handlers::library::scan))
        .route("/api/v1/artwork/:id", get(handlers::artwork::get_artwork))
        .route(
            "/api/v1/library/review/queue",
            get(handlers::review::list_queue),
        )
        .route(
            "/api/v1/library/review/queue/:id",
            get(handlers::review::queue_detail),
        )
        .route(
            "/api/v1/library/review/queue/:id/apply",
            post(handlers::review::apply_review),
        )
        .route(
            "/api/v1/library/overrides",
            post(handlers::review::set_override),
        )
        .route("/api/v1/play", post(handlers::playback::play))
        .route("/stream/direct/:id", get(handlers::playback::stream_direct))
        .route(
            "/sessions/:id/master.m3u8",
            get(handlers::playback::master_playlist),
        )
        .route(
            "/sessions/:id/:segment",
            get(handlers::playback::serve_segment),
        )
        .route(
            "/api/v1/sessions/:id/seek",
            post(handlers::playback::seek_transcode),
        )
        .route(
            "/api/v1/sessions/:id",
            get(handlers::playback::session_detail),
        )
        .route(
            "/api/v1/sessions/:id/resume",
            get(handlers::playback::resume_session),
        )
        .route(
            "/api/v1/sessions/:id/poll",
            get(handlers::playback::poll_session),
        )
        .route(
            "/api/v1/sessions/:id/end",
            post(handlers::playback::end_session),
        )
        .route(
            "/api/v1/servers/register",
            post(handlers::control::register),
        )
        .route("/api/v1/me/servers", get(handlers::control::list))
        .route(
            "/api/v1/servers/register/health",
            get(handlers::control::health),
        )
        .route(
            "/api/v1/servers/register/schema",
            get(handlers::control::schema),
        )
        .route("/api/v1/discovery/search", get(handlers::discovery::search))
        .route(
            "/api/v1/discovery/find",
            get(handlers::discovery::find_media),
        )
        .route(
            "/api/v1/discovery/suggest",
            get(handlers::discovery::suggest),
        )
        .route(
            "/api/v1/discovery/manager-preferences",
            get(handlers::discovery::manager_preferences)
                .post(handlers::discovery::update_manager_preferences),
        )
        .route(
            "/api/v1/find-media/targets",
            get(handlers::discovery::find_media_targets),
        )
        .route(
            "/api/v1/find/targets",
            get(handlers::discovery::find_media_targets),
        )
        .route(
            "/api/v1/find/managers",
            get(handlers::discovery::find_media_targets),
        )
        .route(
            "/api/v1/find-media/search",
            post(handlers::discovery::find_media_search),
        )
        .route(
            "/api/v1/find/search",
            post(handlers::discovery::find_media_search),
        )
        .route(
            "/api/v1/find-media/add",
            post(handlers::discovery::find_media_add),
        )
        .route(
            "/api/v1/find/add",
            post(handlers::discovery::find_media_add),
        )
        .route(
            "/api/v1/find-media/acquisition",
            get(handlers::discovery::find_media_acquisition)
                .post(handlers::acquisition_subscriptions::create_acquisition_intent),
        )
        .route(
            "/api/v1/find-media/acquisition/:intent_id/find-another-release",
            post(handlers::discovery::find_media_acquisition_find_another_release),
        )
        .route(
            "/api/v1/find/acquisition",
            get(handlers::discovery::find_media_acquisition)
                .post(handlers::acquisition_subscriptions::create_acquisition_intent),
        )
        .route(
            "/api/v1/find/acquisition/:intent_id/find-another-release",
            post(handlers::discovery::find_media_acquisition_find_another_release),
        )
        .route(
            "/api/v1/find-media/preferences",
            get(handlers::discovery::find_media_preferences)
                .patch(handlers::discovery::patch_find_media_preferences),
        )
        .route(
            "/api/v1/find/preferences",
            get(handlers::discovery::find_media_preferences)
                .patch(handlers::discovery::patch_find_media_preferences),
        )
        .route("/api/v1/profile/playback", get(handlers::profile::profile))
        .with_state(state)
        .layer(
            CorsLayer::new()
                .allow_origin(Any)
                .allow_methods([Method::GET, Method::POST, Method::PATCH, Method::OPTIONS])
                .allow_headers([header::AUTHORIZATION, header::CONTENT_TYPE]),
        )
}

#[cfg(test)]
mod tests;
